export const serviceData = {
    OPD: [
      "General Cardiology",
      "Interventional Cardiology",
      "Electrophysiology",
      "Heart Failure and Transplant",
      "General Orthopedics",
      "Joint Replacement",
      "Sports Medicine",
      "Pediatric Orthopedics",
      "General Gastroenterology",
      "Hepatology",
      "Pancreatology",
      "Endoscopy",
      "General Neurology",
      "Stroke and Vascular Neurology",
      "Epilepsy",
      "Movement Disorders",
      "General Gynecology",
      "Reproductive Endocrinology",
      "Gynecologic Oncology",
      "Urogynecology",
      "General Urology",
      "Pediatric Urology",
      "Urologic Oncology",
      "Female Urology",
      "General Ophthalmology",
      "Retina and Vitreous",
      "Cornea and External Disease",
      "Glaucoma",
      "General Dermatology",
      "Pediatric Dermatology",
      "Dermatologic Surgery",
      "Cosmetic Dermatology",
      "General ENT",
      "Pediatric ENT",
      "Rhinology",
      "Otology/Neurotology",
      "General Pediatrics",
      "Pediatric Cardiology",
      "Pediatric Endocrinology",
      "Pediatric Gastroenterology",
      "General Pulmonology",
      "Sleep Medicine",
      "Critical Care",
      "Interventional Pulmonology",
      "General Rheumatology",
      "Pediatric Rheumatology",
      "Lupus",
      "Osteoporosis"
    ],
    Surgery: [
      "Coronary Artery Bypass Grafting (CABG)",
      "Heart Valve Repair or Replacement",
      "Aortic Aneurysm Repair",
      "Pacemaker or Defibrillator Implantation",
      "Joint Replacement (Hip, Knee, Shoulder)",
      "Arthroscopy (Knee, Shoulder, Hip)",
      "Spinal Surgery (Discectomy, Spinal Fusion)",
      "Fracture Repair (Open Reduction and Internal Fixation)",
      "Appendectomy",
      "Cholecystectomy (Gallbladder Removal)",
      "Hernia Repair",
      "Mastectomy (Breast Removal)",
      "Bowel Resection",
      "Craniotomy (Brain Surgery)",
      "Spinal Fusion",
      "Deep Brain Stimulation",
      "Aneurysm Clipping",
      "Hysterectomy (Uterus Removal)",
      "Cesarean Section (C-Section)",
      "Oophorectomy (Ovary Removal)",
      "Tubal Ligation",
      "Prostatectomy (Prostate Removal)",
      "Nephrectomy (Kidney Removal)",
      "Cystectomy (Bladder Removal)",
      "Ureteral Stent Placement",
      "Cataract Surgery",
      "LASIK (Laser Eye Surgery)",
      "Glaucoma Surgery",
      "Retinal Detachment Repair",
      "Rhinoplasty (Nose Surgery)",
      "Breast Augmentation or Reduction",
      "Abdominoplasty (Tummy Tuck)",
      "Reconstructive Surgery after Trauma or Cancer",
      "Tonsillectomy",
      "Septoplasty",
      "Cochlear Implants",
      "Sinus Surgery",
      "Congenital Heart Defect Repair",
      "Pyloromyotomy (Pyloric Stenosis Correction)",
      "Pediatric Hernia Repair",
      "Circumcision",
      "Lobectomy (Lung Surgery)",
      "Esophagectomy",
      "Mediastinoscopy",
      "Pleurectomy",
      "Carotid Endarterectomy",
      "Peripheral Bypass Surgery",
      "Endovascular Aneurysm Repair (EVAR)",
      "Varicose Vein Removal"
    ]
  };
  